### ISSUE TITLE
Number of lanes in forward transform

### ISSUE THREAD

**Issue by annymao** [fknorr/ndzip#1]
Hi, 

I'm confused about the function `floor_power_of_two`.  In my understanding, this function will return **the second** highest power of 2 that is less than or equal to input. In the Table 1b of paper, it said that number of lanes equals to Number of threads per thread block. But in the source code, numbers of lanes equals to `floor_power_of_two(# of ThreadsPerBlock=256)`, which equals to 128 in the single precision condition. 
Then when running the function` distributed_for()` in `forward_transform_lanes()`, it will only use half of the threads in the block (that is , only runs the `distribute_for_partial_iteration(range, f)`). 
Is my understanding correct or did I misunderstand anything about the paper or the implementation?

Thank you!

**Comment by fknorr** [comment]
You are right! This is clearly an error in the implementation, now fixed and tested on master (4e6e38e40af7f44fda05569a976445b226275997).

Interestingly, while this is a performance bug on the surface, it does not seem to affect throughput numbers in the relevant 1D and 2D cases in any measurable way on an RTX3090.

Thank you for taking a look at the code in that level of detail!
